# Generated by Django 5.2.1 on 2025-06-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_alter_shortenedurl_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortenedurl',
            name='flag_reason',
            field=models.TextField(blank=True, help_text='Reason for flagging', null=True),
        ),
        migrations.AddField(
            model_name='shortenedurl',
            name='is_flagged',
            field=models.BooleanField(default=False, help_text='URL flagged as potentially malicious'),
        ),
    ]
