# Generated by Django 5.2.1 on 2025-06-16 22:49

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_shortenedurl_flag_reason_shortenedurl_is_flagged'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shortenedurl',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='shortenedurl',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shortenedurl',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='shortenedurl',
            name='flag_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shortenedurl',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shortenedurl',
            name='original_url',
            field=models.URLField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='shortenedurl',
            name='qr_code',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='qr_codes'),
        ),
        migrations.AlterField(
            model_name='shortenedurl',
            name='short_code',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='shortenedurl',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shortened_urls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='shortenedurl',
            index=models.Index(fields=['short_code'], name='shortener_s_short_c_f1ca7f_idx'),
        ),
        migrations.AddIndex(
            model_name='shortenedurl',
            index=models.Index(fields=['user', '-created_at'], name='shortener_s_user_id_ef3a4c_idx'),
        ),
    ]
